### ISSUE TITLE
Speed dating

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/TosterBot#17]
Implement a speed dating mechanism with following features:
- customizable user set for shuffling by: role, connected channel, connected channel cattegory
- customizable size of groups (split into group of 5 be default)
- manual trigger of reshuffle
- possibility of a shuffle order guaranteeing everybody will be with everybody after some number of shuffles

**Comment by krzys-h** [comment]
I would implement this as a separate bot tbh. I don't want it to break if somebody trips the breakers again.

How do you want to handle disconnected users/users disconnecting in the middle of the call? Also, iirc the user has to join a voice channel manually before they can be moved (which makes sense, you don't want the bot to be able to remotely enable your mic and speakers :P), which kinda already defines the user set for you (all users in a specified starting voice channel)

**Comment by krzys-h** [comment]
https://github.com/cytadela8/SpeedDatingBot

**Comment by cytadela8** [comment]
https://github.com/warsztatywww/SpeedDatingBot
