### ISSUE TITLE
Keyword detection does not care about spaces

### ISSUE THREAD

**Issue by krzys-h** [warsztatywww/TosterBot#5]
This is especially visible with things like 'on' or 'off'

**Comment by Matyt** [comment]
Some examples of buggy behaviour induced by simple `word in str`-ish checks:
A message `@Toster, ustaw pseudonim na swoje imię i nazwisko, żebyśmy wiedzieli kim jesteś.` triggers the `'on' in message.content.lower()` condition, hence causes the Toster to turn itself on.
`@Toster, przeczytaj mi historię o Brudnym Harrym.` triggers `'czy' in message.content.lower() and 'brudny' in message.content.lower()`, hence the Toster reports its dirtiness.
`@Tosterze, odpoczywaj sobie do woli (tylko korków nie wywal, dobrze?), a jeśli będziesz potrzebował serwisu, to nas zawołaj.` triggers `'czy' in message.content.lower() and 'ser' in message.content.lower() and '?' in message.content.lower()`, hence the Toster mentions the message's author to assure them that there is a plethora of cheese available.
